# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9OOkAWLmqtl0h42ZMaTQLhD-bmQF83f
"""

import json

lista = []

def salvar_lista():
    with open('lista.json', 'w') as arquivo:
        json.dump(lista, arquivo)
        print("Lista salva com sucesso!")

def carregar_lista():
    try:
        with open('lista.json', 'r') as arquivo:
            return json.load(arquivo)
    except FileNotFoundError:
        return []

def adicionar_produto():
    nome = input("Digite o nome do produto: ")
    qnt = float(input("Digite a quantidade do produto: "))
    produto = {"nome": nome, "qnt": qnt}
    lista.append(produto)
    salvar_lista()
    print("Produto adicionado com sucesso!")

def listar_produtos():
    if not lista:
        print("Nenhum produto cadastrado.")
    else:
        print("\nLista de produtos:")
        for i, produto in enumerate(lista):
            print(f"{i}. Nome: {produto['nome']}, Quantidade: {produto['qnt']}")

def editar_produto():
    listar_produtos()
    try:
        indice = int(input("Digite o índice do produto que deseja editar: "))
        if indice < 0 or indice >= len(lista):
            print("Índice inválido.")
        else:
            nome = input("Digite o novo nome do produto: ")
            qnt = float(input("Digite a nova quantidade do produto: "))
            lista[indice]["nome"] = nome
            lista[indice]["qnt"] = qnt
            salvar_lista()
            print("Produto editado com sucesso!")
    except ValueError:
        print("Por favor, digite um número válido.")

def remover_produto():
    listar_produtos()
    try:
        indice = int(input("Digite o índice do produto que deseja remover: "))
        if indice < 0 or indice >= len(lista):
            print("Índice inválido.")
        else:
            lista.pop(indice)
            salvar_lista()
            print("Produto removido com sucesso!")
    except ValueError:
        print("Por favor, digite um número válido.")

# Carrega a lista ao iniciar o programa
lista = carregar_lista()

# Menu principal
while True:
    print("\nEscolha uma opção:")
    print("1. Adicionar produto")
    print("2. Listar produtos")
    print("3. Editar produto")
    print("4. Remover produto")
    print("5. Salvar lista")
    print("6. Sair")

    opcao = input("Opção: ")

    if opcao == "1":
        adicionar_produto()
    elif opcao == "2":
        listar_produtos()
    elif opcao == "3":
        editar_produto()
    elif opcao == "4":
        remover_produto()
    elif opcao == "5":
        salvar_lista()
    elif opcao == "6":
        print("Saindo...")
        break
    else:
        print("Opção inválida. Tente novamente.")